### PR TITLE
Fix typescript script errors for uninitialised private properties.

### LINKED ISSUE #699: Typescript error with `signature_pad` as project dependency.
**Do you want to request a feature or report a bug?**
Report a Typescript compilation error.

**What is the current behavior?**

When compiling our project which has signature_pad as a dependency, the following typescript error
```typescript

info  - Checking validity of types...
--
125 | Failed to compile.
126 |  
127 | ./node_modules/signature_pad/src/signature_pad.ts:65:11
128 | Type error: Property '_drawningStroke' has no initializer and is not definitely assigned in the constructor.
129 |  
130 | 63 \|   /* tslint:disable: variable-name */
131 | 64 \|   private _ctx: CanvasRenderingContext2D;
132 | > 65 \|   private _drawningStroke: boolean;
133 | \|           ^
134 | 66 \|   private _isEmpty: boolean;
135 | 67 \|   private _lastPoints: Point[]; // Stores up to 4 most recent points; used to generate a new curve
136 | 68 \|   private _data: PointGroup[]; // Stores all points in groups (one group per line or dot)

```

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**
`4.1.4`

### PR DESCRIPTION
**Pull request by paulferrett**
Fixes #699

### CODE REVIEW

File: src/signature_pad.ts [hunk 1]
```diff
@@ -62,12 +62,12 @@ export default class SignaturePad extends SignatureEventTarget {
...
   /* tslint:disable: variable-name */
   private _ctx: CanvasRenderingContext2D;
-  private _drawningStroke: boolean;
-  private _isEmpty: boolean;
-  private _lastPoints: Point[]; // Stores up to 4 most recent points; used to generate a new curve
-  private _data: PointGroup[]; // Stores all points in groups (one group per line or dot)
-  private _lastVelocity: number;
-  private _lastWidth: number;
+  private _drawningStroke = false;
+  private _isEmpty = false;
```
[the remark this answers is not in the document]
Comment (UziTech) [reply src/signature_pad.ts:66]: Could we actually remove `_isEmpty` and just check if `_data` is an empty array?

**Review by UziTech — CHANGES_REQUESTED** [review]

File: package.json [hunk 2]
```diff
@@ -1,8 +1,8 @@
 {
-  "name": "signature_pad",
+  "name": "@ptgs/signature_pad",
```
Comment (UziTech) [inline package.json:2]: Remove these changes

**Review by UziTech — CHANGES_REQUESTED** [review]

File: package.json (hunk 2 above)
Comment (paulferrett) [reply package.json:2]: Ah sorry, these were only meant to be in my main so I could publish in the meantime. Will fix up.

**Review by UziTech — APPROVED** [review]
